apiVersion: v1
entries:
  apm-server:
  - apiVersion: v1
    appVersion: 8.5.1
    created: "2022-12-06T09:25:52.699613942Z"
    description: Official Elastic helm chart for Elastic APM Server
    digest: d0da01aba323241cba744611d089d751a972e39bc08457fe9c309d385d1e495c
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/apm.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: apm-server
    sources:
    - https://github.com/elastic/apm
    urls:
    - https://nobidev.github.io/elastic-helm-charts/charts/apm-server-8.5.1.tgz
    version: 8.5.1
  elasticsearch:
  - apiVersion: v1
    appVersion: 8.5.1
    created: "2022-12-06T09:25:52.70236397Z"
    description: Official Elastic helm chart for Elasticsearch
    digest: 08f4879176f3bb6c7b212d79a2c519e608edb1aa24313494bc34cdcb21644d81
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/elasticsearch.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: elasticsearch
    sources:
    - https://github.com/elastic/elasticsearch
    urls:
    - https://nobidev.github.io/elastic-helm-charts/charts/elasticsearch-8.5.1.tgz
    version: 8.5.1
  filebeat:
  - apiVersion: v1
    appVersion: 8.5.1
    created: "2022-12-06T09:25:52.704182388Z"
    description: Official Elastic helm chart for Filebeat
    digest: aab5f4cd97441c2e722cdff1eb6ab0601bf44a996bd501aa83c41e0f0243320e
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/beats.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: filebeat
    sources:
    - https://github.com/elastic/beats
    urls:
    - https://nobidev.github.io/elastic-helm-charts/charts/filebeat-8.5.1.tgz
    version: 8.5.1
  kibana:
  - apiVersion: v1
    appVersion: 8.5.1
    created: "2022-12-06T09:25:52.705843304Z"
    description: Official Elastic helm chart for Kibana
    digest: a732f491a5a1e14042279f32987b6edc74c2668312baf65c1d38bb45a0f8c45b
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/kibana.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: kibana
    sources:
    - https://github.com/elastic/kibana
    urls:
    - https://nobidev.github.io/elastic-helm-charts/charts/kibana-8.5.1.tgz
    version: 8.5.1
  logstash:
  - apiVersion: v1
    appVersion: 8.5.1
    created: "2022-12-06T09:25:52.707853324Z"
    description: Official Elastic helm chart for Logstash
    digest: 9ad97f64f3bbd198e261633847784b3c284ae770efb2b02360dfd086a3449031
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/logstash.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: logstash
    sources:
    - https://github.com/elastic/logstash
    urls:
    - https://nobidev.github.io/elastic-helm-charts/charts/logstash-8.5.1.tgz
    version: 8.5.1
  metricbeat:
  - apiVersion: v1
    appVersion: 8.5.1
    created: "2022-12-06T09:25:52.713529481Z"
    dependencies:
    - condition: kube_state_metrics.enabled
      name: kube-state-metrics
      repository: https://prometheus-community.github.io/helm-charts
      version: 4.7.0
    description: Official Elastic helm chart for Metricbeat
    digest: ef1de52c9a4aabdb9343075753d3988f91a4c3a1c79727f9a51af6d790eb9381
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/beats.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: metricbeat
    sources:
    - https://github.com/elastic/beats
    urls:
    - https://nobidev.github.io/elastic-helm-charts/charts/metricbeat-8.5.1.tgz
    version: 8.5.1
generated: "2022-12-06T09:25:52.698177028Z"
